change from general shell to bash

diff --git a/pushover b/pushover
--- a/pushover
+++ b/pushover
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # define config files
 GLOBAL_CONFIG=/etc/pushoverrc
@@ -17,44 +17,38 @@ usage () {
 }
 
 # check if any help argument is given then print usage message
-if [ "$1" = "-h" ] && [ "$1" = "--help" ]
-then
+if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
     usage
     exit
 fi
 
 # check if global configuration file is available and source it
-if [ -f "$GLOBAL_CONFIG" ]
-then
+if [[ -f "$GLOBAL_CONFIG" ]]; then
     . $GLOBAL_CONFIG
-    GLOBAL_CONFIG_LOADED=1
+    GLOBAL_CONFIG_LOADED=true
 fi
 
 # check if user configuration file is available and source it
-if [ -f "$USER_CONFIG" ]
-then
+if [[ -f "$USER_CONFIG" ]]; then
     . $USER_CONFIG
-    USER_CONFIG_LOADED=1
+    USER_CONFIG_LOADED=true
 fi
 
 # check if any config is loaded
-if [ "$GLOBAL_CONFIG_LOADED" = false ] && [ "$USER_CONFIG_LOADED" = false ]
-then
-    echo "No configuration file was loaded"
+if [[ $GLOBAL_CONFIG_LOADED == false ]] && [[ $USER_CONFIG_LOADED == false ]]; then
+    echo >&2 "No configuration file was loaded"
     exit 2
 fi
 
 # check if the application token is configured
-if [ -z "$APP_TOKEN" ]
-then
-    echo "No application token is configured"
+if [[ -z "$APP_TOKEN" ]]; then
+    echo >&2 "No application token is configured"
     exit 3
 fi
 
 # check if the user key is configured
-if [ -z "$USER_KEY" ]
-then
-    echo "No user key is configured"
+if [[ -z "$USER_KEY" ]]; then
+    echo >&2 "No user key is configured"
     exit 3
 fi
 
@@ -62,10 +56,9 @@ fi
 MESSAGE=$1
 
 # if no message is given print error and usage message
-if [ -z "$MESSAGE" ]
-then
-    echo "Message can't be empty"
-    usage
+if [[ -z "$MESSAGE" ]]; then
+    echo >&2 "Message can't be empty"
+    usage >&2
     exit 1
 fi
 
